---
kind: pipeline
name: Lint

platform:
  os: linux
  arch: amd64

steps:
- name: CentOS 7
  image: hashicorp/packer
  commands:
  - apk --no-cache add --update python3
  - pip3 install --upgrade pip
  - pip3 install invoke
  - inv build-aws --validate --distro=centos --distro-version=7
  depends_on:
  - clone

---
kind: pipeline
name: CentOS 7

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed openssh-client python3
  - pip3 install --upgrade pip
  - pip3 install invoke
  - "echo \"$SSHKEY\" > sre-jenkins-key"
  - "echo \"$GPGKEY\" > gpgkey.asc"
  - chmod 600 sre-jenkins-key gpgkey.asc
  - "ssh-keyscan -t rsa github.com | ssh-keygen -lf -"
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"
  - inv build-aws --distro=centos --distro-version=7
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
    GPGKEY:
      from_secret: gpgkey
    SSHKEY:
      from_secret: sshkey
  depends_on:
  - clone

trigger:
  event:
  - tag
  ref:
  - "refs/tags/aws-jenkins-slave-v1.*"

depends_on:
- Lint

---
kind: pipeline
name: CentOS 7 (Staging)

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed openssh-client python3
  - pip3 install --upgrade pip
  - pip3 install invoke
  - "echo \"$SSHKEY\" > sre-jenkins-key"
  - "echo \"$GPGKEY\" > gpgkey.asc"
  - chmod 600 sre-jenkins-key gpgkey.asc
  - "ssh-keyscan -t rsa github.com | ssh-keygen -lf -"
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"
  - inv build-aws --staging --distro=centos --distro-version=7
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
    GPGKEY:
      from_secret: gpgkey
    SSHKEY:
      from_secret: sshkey
  depends_on:
  - clone

trigger:
  branch:
  - jenkins-slaves
  event:
  - push

depends_on:
- Lint

---
kind: signature
hmac: 50894dbbb321def80aeac6832415c6a407bf0302e0ddda6655976a88ad1b91a3

...
