---
kind: pipeline
name: lint-arch-2019-01-09

platform:
  os: linux
  arch: amd64

steps:
- name: lint-arch-2019-01-09
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=arch OS_REV=2019-01-09
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-centos-6

platform:
  os: linux
  arch: amd64

steps:
- name: lint-centos-6
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=centos OS_REV=6
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-centos-7

platform:
  os: linux
  arch: amd64

steps:
- name: lint-centos-7
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=centos OS_REV=7
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-debian-8

platform:
  os: linux
  arch: amd64

steps:
- name: lint-debian-8
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=debian OS_REV=8
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-debian-9

platform:
  os: linux
  arch: amd64

steps:
- name: lint-debian-9
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=debian OS_REV=9
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-fedora-28

platform:
  os: linux
  arch: amd64

steps:
- name: lint-fedora-28
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=fedora OS_REV=28
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-fedora-29

platform:
  os: linux
  arch: amd64

steps:
- name: lint-fedora-29
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=fedora OS_REV=29
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-opensuse-15

platform:
  os: linux
  arch: amd64

steps:
- name: lint-opensuse-15
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=opensuse OS_REV=15
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-opensuse-42.3

platform:
  os: linux
  arch: amd64

steps:
- name: lint-opensuse-42.3
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=opensuse OS_REV=42.3
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-ubuntu-1404

platform:
  os: linux
  arch: amd64

steps:
- name: lint-ubuntu-1404
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=ubuntu OS_REV=1404
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-ubuntu-1604

platform:
  os: linux
  arch: amd64

steps:
- name: lint-ubuntu-1604
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=ubuntu OS_REV=1604
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-ubuntu-1804

platform:
  os: linux
  arch: amd64

steps:
- name: lint-ubuntu-1804
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=ubuntu OS_REV=1804
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-windows-2019

platform:
  os: linux
  arch: amd64

steps:
- name: lint-windows-2019
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=windows OS_REV=2019
  when:
    event:
    - pull_request

---
kind: pipeline
name: lint-windows-2012r2

platform:
  os: linux
  arch: amd64

steps:
- name: lint-windows-2012r2
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=windows OS_REV=2012r2
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-arch-2019-01-09

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=arch OS_REV=2019-01-09
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-centos-6

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=centos OS_REV=6
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-centos-7

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=centos OS_REV=7
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-debian-8

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=debian OS_REV=8
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-debian-9

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=debian OS_REV=9
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-fedora-28

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=fedora OS_REV=28
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-fedora-29

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=fedora OS_REV=29
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-opensuse-15

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=opensuse OS_REV=15
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-opensuse-42.3

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=opensuse OS_REV=42.3
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-ubuntu-1404

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=ubuntu OS_REV=1404
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-ubuntu-1604

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=ubuntu OS_REV=1604
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-ubuntu-1804

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=ubuntu OS_REV=1804
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-windows-2019

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=windows OS_REV=2019
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: pipeline
name: build-windows-2012r2

platform:
  os: linux
  arch: amd64

steps:
- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make build OS=windows OS_REV=2012r2
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  when:
    ref:
    - "refs/tags/v1.*"

---
kind: secret
type: general
data:
  password: >
    Aazhz_Ygq86WGzCbbjUgM07opxi05uFzSx_ymHgdA8cQPxm0dK3MUehJH8e_
    nLMBJspfPVJ68YDBibQ1ZW9G2VGBXZUdHZzF34N69exdEA==
  username: >
    lX3OCQrobO2Qtj4y29iF5kwFWQxutX27rOBzFehcoOqCqRdScn-p99l04WZR
    nNLuFqP25_qJiet_sHg=

---
kind: signature
hmac: 44579521e432b4f7b9c372dae0d75735dd35229a55bfe83d059d76a16c0f5538

...
