---
kind: pipeline
name: Lint

platform:
  os: linux
  arch: amd64

steps:
- name: CentOS 7
  image: hashicorp/packer
  commands:
  - apk --no-cache add --update python3
  - python3 -m ensurepip
  - "rm -r /usr/lib/python*/ensurepip"
  - pip3 install --upgrade pip setuptools
  - pip3 install invoke
  - inv build-aws --validate --distro=centos --distro-version=7
  depends_on:
  - clone

---
kind: pipeline
name: CentOS 7

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 0 seconds; sleep 0'"

- name: slave-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed openssh-client
  - apk --no-cache add --update python3
  - python3 -m ensurepip
  - "rm -r /usr/lib/python*/ensurepip"
  - pip3 install --upgrade pip setuptools
  - pip3 install invoke
  - "printf \"$SSHKEY\" > sre-jenkins-key"
  - echo ---
  - head -c 150 sre-jenkins-key
  - echo ---
  - "printf \"$GPGKEY\" > gpgkey.asc"
  - echo ---
  - head -c 150 gpgkey.asc
  - echo ---
  - chmod 600 sre-jenkins-key gpgkey.asc
  - "ssh-keyscan -t rsa github.com | ssh-keygen -lf -"
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"
  - inv build-aws --distro=centos --distro-version=7
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
    GPGKEY:
      from_secret: gpgkey
    SSHKEY:
      from_secret: sshkey
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/aws-jenkins-slave-v1.*"

depends_on:
- Lint

---
kind: pipeline
name: CentOS 7 (Staging)

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 0 seconds; sleep 0'"

- name: slave-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed openssh-client
  - apk --no-cache add --update python3
  - python3 -m ensurepip
  - "rm -r /usr/lib/python*/ensurepip"
  - pip3 install --upgrade pip setuptools
  - pip3 install invoke
  - "printf \"$SSHKEY\" > sre-jenkins-key"
  - echo ---
  - head -c 150 sre-jenkins-key
  - echo ---
  - "printf \"$GPGKEY\" > gpgkey.asc"
  - echo ---
  - head -c 150 gpgkey.asc
  - echo ---
  - chmod 600 sre-jenkins-key gpgkey.asc
  - "ssh-keyscan -t rsa github.com | ssh-keygen -lf -"
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"
  - inv build-aws --staging --distro=centos --distro-version=7
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
    GPGKEY:
      from_secret: gpgkey
    SSHKEY:
      from_secret: sshkey
  depends_on:
  - throttle-build

trigger:
  branch:
  - jenkins-slaves
  event:
  - push

depends_on:
- Lint

---
kind: signature
hmac: 7a90633ad5a3f1a0b6e4c360460afe25c65867acc6a593ca261a88c09105215e

...
