---
kind: pipeline
name: packer-lint
steps:
- name: lint-packer-os-images
  image: hashicorp/packer

  commands:
  - apk --no-cache add make
  - make validate OS=centos OS_REV=6
  - make validate OS=centos OS_REV=7
  - make validate OS=debian OS_REV=8
  - make validate OS=debian OS_REV=9
  - make validate OS=fedora OS_REV=28
  - make validate OS=fedora OS_REV=29
  - make validate OS=opensuse OS_REV=42.3
  - make validate OS=ubuntu OS_REV=1404
  - make validate OS=ubuntu OS_REV=1604
  - make validate OS=ubuntu OS_REV=1804
  when:
    event:
    - pull_request
---
kind: signature
hmac: 69a43960e44576bbe7d587aeda4a170821ac47b1fb99e9321b5998fcb4e62a83

...
