---
kind: pipeline
name: Lint

platform:
  os: linux
  arch: amd64

steps:
- name: Arch
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=arch OS_REV=2019-01-09
  depends_on:
  - clone

- name: CentOS 6
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=centos OS_REV=6
  depends_on:
  - clone

- name: CentOS 7
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=centos OS_REV=7
  depends_on:
  - clone

- name: Debian 8
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=debian OS_REV=8
  depends_on:
  - clone

- name: Debian 9
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=debian OS_REV=9
  depends_on:
  - clone

- name: Fedora 28
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=fedora OS_REV=28
  depends_on:
  - clone

- name: Fedora 29
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=fedora OS_REV=29
  depends_on:
  - clone

- name: Opensuse 15
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=opensuse OS_REV=15
  depends_on:
  - clone

- name: Opensuse 42.3
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=opensuse OS_REV=42.3
  depends_on:
  - clone

- name: Ubuntu 1404
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=ubuntu OS_REV=1404
  depends_on:
  - clone

- name: Ubuntu 1604
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=ubuntu OS_REV=1604
  depends_on:
  - clone

- name: Ubuntu 1804
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=ubuntu OS_REV=1804
  depends_on:
  - clone

- name: Windows 2012r2
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=windows OS_REV=2012r2
  depends_on:
  - clone

- name: Windows 2016
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=windows OS_REV=2016
  depends_on:
  - clone

- name: Windows 2019
  image: hashicorp/packer
  commands:
  - apk --no-cache add make
  - make validate OS=windows OS_REV=2019
  depends_on:
  - clone

---
kind: pipeline
name: Arch

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 5 seconds; sleep 5'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=arch OS_REV=2019-01-09
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: CentOS 6

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 10 seconds; sleep 10'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=centos OS_REV=6
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: CentOS 7

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 15 seconds; sleep 15'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=centos OS_REV=7
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Debian 8

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 20 seconds; sleep 20'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=debian OS_REV=8
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Debian 9

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 25 seconds; sleep 25'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=debian OS_REV=9
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Fedora 28

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 30 seconds; sleep 30'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=fedora OS_REV=28
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Fedora 29

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 35 seconds; sleep 35'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=fedora OS_REV=29
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Opensuse 15

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 40 seconds; sleep 40'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=opensuse OS_REV=15
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Opensuse 42.3

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 45 seconds; sleep 45'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=opensuse OS_REV=42.3
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Ubuntu 1404

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 50 seconds; sleep 50'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=ubuntu OS_REV=1404
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Ubuntu 1604

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 55 seconds; sleep 55'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=ubuntu OS_REV=1604
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Ubuntu 1804

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 60 seconds; sleep 60'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=ubuntu OS_REV=1804
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Windows 2012r2

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 0 seconds; sleep 0'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=windows OS_REV=2012r2
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Windows 2016

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 0 seconds; sleep 0'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=windows OS_REV=2016
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: pipeline
name: Windows 2019

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 0 seconds; sleep 0'"

- name: base-image
  image: hashicorp/packer
  commands:
  - apk --no-cache add make curl grep gawk sed
  - make build-staging OS=windows OS_REV=2019
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: username
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: password
  depends_on:
  - throttle-build

trigger:
  event:
  - tag
  ref:
  - "refs/tags/v1.*"

depends_on:
- Lint

---
kind: secret
type: general
data:
  password: >
    ood6DhiPeWBKZfSOqhsq-iJPmkfnrbdIonynU7Hdd_gTk4eeii_l4cbit9O3
    s5P-iX3CWa_v6RwKtKz9vQd6V0MuphwGxRAcSC1z4O3R0g==
  username: >
    I0tTPep0OuH_qwx5v5-cr4gONWEDbccbJ4yShpI369wV5WYYRuq1Gckx40A6
    _OK_ypQ4AfAiDjEsC2U=

---
kind: signature
hmac: 35afa8523a8a7a21ea8cdfa24c106a0306f0dc0dea90dd89f78122705642e08f

...
